### ISSUE TITLE
S3 transfers hang

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1002]
I am running pageflow in docker containers with the following configuration:
container 1: web app with puma server
container 2: resque scheduler
container 3: resque worker
container 4: nginx for proxy
database: RDS postgres

I can upload an image, but when I try to upload a video, it says successfully uploaded, but the S3 transfer never finishes.

Advice? I don't see anything helpful in slow.log, just lots of result pending.

Thank you.

**Comment by tf** [comment]
See [Distributing Resque Workers](https://github.com/codevise/pageflow/wiki/Distributing-Resque-Workers). The wiki entry does not explicitly handle the Docker case, but the issue is the same. You will need to add a shared volume to your web app and Resque worker containers, so that files uploaded to a web app container become visible for Resque workers. Pageflow does not support direct upload to S3 at the moment (#886), which would be the nicer solution long term.

**Comment by tim-wgbh** [comment]
Thank you
