### ISSUE TITLE
500 error on content save

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1033]
Our editor saw this error when saving a text page:
![screen shot 2018-10-22 at 1 30 27 pm](https://user-images.githubusercontent.com/11877425/47309710-2ba0bb00-d603-11e8-9ab9-1cbef62857a7.jpg)

I traced it to an unloaded concern method, #verify_edit_lock!:

![screen shot 2018-10-22 at 1 29 00 pm](https://user-images.githubusercontent.com/11877425/47309745-407d4e80-d603-11e8-84f8-6254d42f3445.jpg)

Do you know why this might be happening?  Thank you.

**Comment by tf** [comment]
Never seen that before. The `EditLocking` concern is included in `Pageflow::ApplicationController` which `PagesController` inherits from. So that looks all fine. Might be some funky code reloading issue? Are you running in production environment?

**Comment by tim-wgbh** [comment]
Yes, I am. I haven't seen that until now, either. The only thing that I can think might be the cause is that I needed to add Google Tag Manager, so I'm running my own layout template in 
_views > layouts > pageflow > themes > nova >_
I'm wondering if there's some react code that then doesn't know where to find the concern.

**Comment by tf** [comment]
Not clear to me how this could be related to React. Maybe there is something getting in the way of eager loading `Pageflow::ApplicationController`? Or something causing `Pageflow::ApplicationController` to be redefined without including the concern? Hard to say actually. If the problem only happened once, I'd lean towards closing this issue. Feel free to report back once the issue surfaces again.

**Comment by tim-wgbh** [comment]
Sorry, I was not clear - I just mentioned React because the save happens via AJAX. 

I made the following changes to my code:
Added layout template containing GTM snippets:
/app/views/layouts/pageflow/themes/nova/application.html.erb_

Modified the application controller to use this layout template:
```
module Pageflow
  class Applicationcontroller < ActionController::Base
    layout 'pageflow/themes/nova/application'
  end
end
```
This results in the verify_edit_lock! method being unknown, which indicates that that concern is not being loaded., and somehow the layout spec is preventing that.

Thank you.

**Comment by tf** [comment]
In development mode this can definitely cause Pageflow's `ApplicationController` not to be auto loaded since you already defined the constant. In production mode, I would expect eager loading to work anyway, but maybe I am missing something. Generally speaking, I think it is safer practice to `include` concerns in an initializer to patch some library's classes rather than trying to reopen classes and risking to break auto loading. In this case the even simpler approach might be to override `layouts/pageflow/application.html.erb` by creating a template with this name in your `app/views` directory. You are changing the layout for all entries anyway - independent of the theme.

Still, please note that overriding templates like that basically means you will need to manually port changes on future updates. Pageflow provides [some partials](https://github.com/codevise/pageflow/wiki/Customizing-Views) as extension points which are empty by default and should be safer to override.

**Comment by tf** [comment]
And for everything even slightly more complicated, [creating a custom widget type](https://github.com/codevise/pageflow/blob/master/doc/creating_widget_types.md) is probably the best option.
