### ISSUE TITLE
Next steps after rails generate pageflow:install

### ISSUE THREAD

**Issue by thuerkow** [codevise/pageflow#1074]
Hi guys,

I'm not sure about the next steps after:

`rails generate pageflow:install`

The 
`rake db:seed`

is aborting with the following error:

> SyntaxError: /var/lib/gems/2.5.0/gems/devise-3.5.10/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end
...ter only: [:create, :destroy] { request.env["devise.skip_tim...
...                              ^
/var/lib/gems/2.5.0/gems/devise-3.5.10/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }

Can you explain me how to see my pageflow installation in the browser? I think there is something missing in the pageflow installation introduction.

Thanks for helping me out!

**Comment by tf** [comment]
Pageflow 12 (or more specifically Devise 3.5 which Pageflow 12 depends on) does not support Ruby 2.5. You need use Ruby 2.3 or wait for Pageflow 13 to be released. When viewing the README, watch out to use the reversion [from the `12-x-stable` branch](https://github.com/codevise/pageflow/blob/12-x-stable/README.md), since the README on master already contains a working draft of setup instructions for Pageflow 13.
