### ISSUE TITLE
iOS 8: window.onload not Triggered if Audio Tag on Page

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#118]
Under iOS 8.0.2 entries containing audio pages get stuck at the loading spinner since Safari fails to trigger the `onload` event on `window`. The problem does not occur if the page does not contain audio tags.

As a first workaround we'll hide the loading spinner after a timeout for iOS 8 browsers. As a more profound fix, one could consider creating audio tags dynamically (the way video tags are already handled now). This would require more browser testing though.

**Comment by lufes** [comment]
The problem is related to the window.onload event, which will not be triggered if there's a video or audio with the preload="none" attribute set. window.onload will run once every asset is loaded, and iOS 8 keeps waiting for the video to load, which will never do. Submitting a ticket to Apple right now.

**Comment by sprt** [comment]
@lufes Link to the ticket?
