### ISSUE TITLE
Factory girl looking for et.ogg

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#365]
I have just installed `factory_girl_rails` into my app (i.e. not Pageflow, but the Rails app) and suddenly I get this error:

```
17:41 $ bundle exec rake cucumber --trace
** Invoke cucumber (first_time)
** Invoke cucumber:ok (first_time)
** Invoke test:prepare (first_time)
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/joost/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pageflow-0.8.1/spec/fixtures/et.ogg
/Users/joost/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pageflow-0.8.1/spec/factories/audio_files.rb:7:in `initialize'
```

which makes sense, because that file is not in the engine's fixtures folder, but in the engine's factories folder. Any idea why I would see this error though? I don't run the engine's tests at all but clearly Factory Girl is digging into it and finds the factories.

**Comment by tf** [comment]
Hi Joost,

sorry for the late response. I think you are seeing this error because the `spec/fixtures` folder is not [included in the gem](https://github.com/codevise/pageflow/blob/master/pageflow.gemspec#L13). For now you can work around this by using a git source in your `Gemfile`, but we should definitely add the fixtures to the gem.

Just so you know: the Factory Girl definitions are added via the [Pageflow engine](https://github.com/codevise/pageflow/blob/master/lib/pageflow/engine.rb#L78) at the moment. I've since started collecting other development dependencies for Pageflow plugins inside a separate [`pageflow-support`](https://github.com/codevise/pageflow/blob/master/spec/support/pageflow-support.gemspec) gem. It would make more sense to move the factory definitions (and fixtures) into that gem. That way, adding Pageflow to an application's `Gemfile` would not automatically register the factories and prevent namespace collisions in case you already have an `entry`, `page` etc. factory.

Cheers

**Comment by tilsammans** [comment]
I didn't know that FactoryGirl was being configured in `engine.rb`. Couldn't you better put it in the engine's `config/environments/development.rb`?

Anyway, the pageflow-support (or pageflow-devel?) approach sounds good as a long-term solution. For the short term, will adding the fixtures to the pageflow gem fix it? I could make that change quite quickly, but since it's such a small thing there must be a reason you didn't do it? Just making sure we're aligned...

**Comment by tf** [comment]
Yes, I simply forgot and didn't notice since we use git sources in our Gemfiles most of the time. If you have the time, I'd be happy to accept a PR, or even better two: one that fixes it on `master` and another backporting the change to the `0-8-stable` branch. Then I can release 0.8.2 tonight. Thanks!

**Comment by tilsammans** [comment]
No problem.

**Comment by tilsammans** [comment]
See #368 and #369 

I was also wondering if we should change https://github.com/codevise/pageflow/blob/master/pageflow.gemspec#L14 into `Dir['spec/**/*']`?

**Comment by tf** [comment]
Thanks for the PRs. I've released 0.8.2. Can you verify that this fixes the problem?

Looking at [this SO question](http://stackoverflow.com/questions/18871541/what-is-the-purpose-of-test-files-configuration-in-a-gemspec) I wonder if we should simply delete the `test_files` line. The way I understand it, `test_files` are also installed along with the gem, which seems like extra baggage to me.

**Comment by tilsammans** [comment]
**YES**! 0.8.2 fixes the issue! :tada: 

`test_files` is [not present in the specification](http://guides.rubygems.org/specification-reference/) at all anymore. I'd say it can safely be dropped.

**Comment by tf** [comment]
That's great to hear! 

I'll remove the useless `test_files` attribute now (#370). Also, I noticed that Readme and Changelog were not included in the gem. Not really sure where this could be helpful, but it feels like those should also be in there (#371).

**Comment by tf** [comment]
The only downside of adding the fixtures is that we now include a 4MB fixture video in the gem... I should probably look into moving the factories out of the main gem when I get a chance.

**Comment by tilsammans** [comment]
Yes, I didn't fully realise. It's not horrible but it's not a long term solution either. If I can be helpful, I'd love to contribute.

**Comment by tf** [comment]
We are always happy to accept contributions! I wonder if we should create more issues for planned or possible features and additions. Maybe even for small stuff like this. It might help coordinate and encourage contributions. On the other hand, I do not want to litter the issue tracker  with vague "wish list" issues nobody is working on actively...

**Comment by tilsammans** [comment]
A public Trello board? It might be a little too much procedure. I'm happy to just exchange email for the time being.
