### ISSUE TITLE
Migration fails on users table

### ISSUE THREAD

**Issue by dittmanc** [codevise/pageflow#367]
Following the readme steps the users table is not being created during rake db:migrate:

Mysql::Error: Table 'test_pageflow_development.users' doesn't exist: ALTER TABLE `users` ADD `failed_attempts` int(11) DEFAULT 0/usr/local/share/gems/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:301:in `query'

**Comment by dittmanc** [comment]
Manually adding this table with the column email as a PRIMARY KEY is necessary to successfully complete this migration.

**Comment by tf** [comment]
This has come up a couple of times already: #314, #292, #9. It is most likely related to ["Devise Migration without File Extension"](https://github.com/codevise/pageflow/wiki/Troubleshooting#devise-migration-without-file-extension) from our trouble shooting guide. Did you apply the migration name fix as [mentioned in the README](https://github.com/codevise/pageflow#database-migration)?

Start with a newly generated Rails application when you retry the process, since Devise will try to detect an existing `app/models/user.rb` file and will try to add fields to the user model. This does not work though if your db schema is in an invalid state.

**Comment by dittmanc** [comment]
Thanks this was the issue. I had made a typo when I ran the step to fix the file extension and mangled the file.
