### ISSUE TITLE
Allow SSL for published entries

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#388]
A private controller method named `prevent_ssl` is used in two places. I was wondering why? We have our entire site behind SSL and this is causing problems.

https://github.com/codevise/pageflow/blob/1babee2a31d78d2ce509af849733a5a104484093/app/controllers/pageflow/application_controller.rb#L57

**Comment by tf** [comment]
We have always been serving assets over CDN endpoints which do not support HTTPS. To prevent mixed content warnings we chose to redirect back to HTTP for published pageflows. I agree, though, that this should be configurable via some kind of `Pageflow.config.prevent_ssl_for_public_sites` setting, which should default to `true` for backward compatibility. If you are interested in looking into that, I could give you a few more ideas how I'd implement and test this feature.

**Comment by tilsammans** [comment]
We went the other way, force https for everyone, and use the secure endpoints on CloudFront.

Sure, I can work on that feature. It won't be today or tomorrow (and I monkey-patched the gem, don't tell anyone) but I'd like to solve it cleanly. Any pointers are welcome.


Op 20 aug. 2015, om 10:45 heeft Tim Fischbach <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


We have always been serving assets over CDN endpoints which do not support HTTPS. To prevent mixed content warnings we chose to redirect back to HTTP for published pageflows. I agree, though, that this should be configurable via some kind of Pageflow.config.prevent_ssl_for_public_sites setting, which should default to true for backward compatibility. If you are interested in looking into that, I could give you a few more ideas how I'd implement and test this feature.

**Comment by tf** [comment]
Great. And it shouldn't be too complicated either. Maybe there should then even be three possible values for some `public_entry_ssl_mode` like `:allow`, `:prevent` and `:enforce`?

Anyway, the additional config option would go into [`Pageflow::Configuration`](https://github.com/codevise/pageflow/blob/master/lib/pageflow/configuration.rb). The `preven_ssl` could be renamed and moved from the application controller junk drawer to some controller concern module which could be mixed into `Pageflow::EntriesController` and `Pageflow::FilesController`. 

We should test the different redirects at controller level, possibly with a shared example group. `Pageflow.config` can simply be manipulated inside the test setup since it is reset before ever example run.
