### ISSUE TITLE
Gradient opacity default

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#414]
Right now the gradient for the background-image page type defaults to 100%.

Maybe this is just us, but a 100% opacity is the exception and not the rule. It would save some time to have this default to 0%. Is there any way to set this as a default value?

![schermafbeelding 2015-10-19 om 11 26 55](https://cloud.githubusercontent.com/assets/14680/10574214/ede16cda-7654-11e5-8008-d08c7877587c.png)

**Comment by tf** [comment]
Hm, it would be nice make bits like this more flexible. At the moment the default is [simply hard coded](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/editor/models/configuration.js#L8). Changing the default to 0% globally is not really an option for us as the gradient ensures sufficient contrast. So while I agree "100% opacity" is often not pretty, it is the safest choice from an accessibility perspective.

So if there was some mechanism to define defaults either on a per installation, per account or per entry basis, we might leave the choice to somebody else, but I guess implementing something like that might not be that easy.

**Comment by tilsammans** [comment]
What I was thinking, but not sure how possible this is, is to have each Page Type have it's own [Configurable](http://api.rubyonrails.org/classes/ActiveSupport/Configurable.html) object that holds these defaults. The defaults then can be overridden using simple initializers. Would that work?

**Comment by tf** [comment]
I played around with an [idea along thoise lines](https://github.com/codevise/pageflow/commit/30db4eb7613a86b1fafc2bcb9c185d453e499330) once, but did not go through with it since I found no good way to actually set those default.  `Backbone.Model#defaults` is only evaluated once on model creation and then saved to the actual attributes. But the defaults must change when the page type changes. I tried [setting attributes explicitly on page type change](https://github.com/codevise/pageflow/commit/30db4eb7613a86b1fafc2bcb9c185d453e499330#diff-38d956dc71a3295478f4a2f2d9b24598R34), but that is also inconsistent since we do not want to reset attributes that have already been adjusted.

There would need to be some way to merge in the defaults when the configuration is read, but not actually persist it. But I'm not sure how. Probably this could be solved somehow at the Backbone Model layer.

**Comment by tilsammans** [comment]
I'm afraid this is a little too much out of my comfort zone. It would be nice if it were to become configurable, though.

**Comment by tf** [comment]
Yeah, it would sure be nice. Still, I'm tempted to close this issue since it's not really actionable right now. Alternatively, we could keep it around with a "help wanted" label. But I don't want those to pile up too much, especially when I have no concrete idea how someone willing to help should approach the issue.

**Comment by tilsammans** [comment]
Agreed with closing it, at least for now.
