### ISSUE TITLE
Make the loading spinner more customizable

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#438]
Currently the loading spinner has [inline CSS hardcoded](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/pageflow/entries/_loading_spinner.html.erb). This makes it a little tricky to customize. Is there a particular reason for it? When I hack it out, the spinner works just fine.

Furthermore we use a [JavaScript fade](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/assets/javascripts/pageflow/widgets/loading_spinner.js) but a CSS animation for the rotation. Why not a simple CSS opacity fade as well?

Then we have an [inline script](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/layouts/pageflow/_loading_spinner_inline_script.html.erb) that does a document write for a reason unknown to me (I am sure it serves a function, but on modern browsers does not make a difference).

Could we aim for a simple, documented structure for the loading spinner so it can be further customized per theme? And drop legacy (IMO) document writes and JS fades?

```
<div class="loading_spinner" id="loading_spinner">
  <div class="loading_spinner_inner">
    <div></div>
  </div>
</div>
```

would be okay with me, even if it's a little rich, this is exactly what we have now, with the inline CSS removed. If that can be moved to the theme, it would be a lot easier to override.

I can work on this if you'd like.

**Comment by tf** [comment]
I agree that the loading spinner is a bit of a tricky issue. Maybe let me go into some of the thinking that lead to the current solution.

> the loading spinner has inline CSS hardcoded

For our initial customers it was a high priority that no incompletely loaded content would be displayed on page load. If we moved the inline styles into the theme, page content could be visible while the stylesheet has not been loaded yet.

Which of these inline styles hinder customization most here? The background color? 

> we use a JavaScript fade

This really is a CSS transition. We only add the `fade` CSS class once the `pageflow.ready` promise has been resolved.

> inline script that does a document write

This arguably ugly piece is meant to make the non js case work. If the user does not have JS enabled we have to make sure the loading spinner will not cover the page indefinitely. So the spinner is [`display: none` by default](https://github.com/codevise/pageflow/blob/master/app/assets/stylesheets/pageflow/loading_spinner.css.scss#L2). Again, in order to prevent incompletely loaded content from flashing, we have to display it as soon as possible after page load, but only if JS is enabled. Inserting an inline script via `document.write` makes this possible.

I hope this helps to shed some light on the implementation details.

**Comment by tf** [comment]
Shall this issue remain open? As it stands, it is not really actionable - at least not to me.

**Comment by tilsammans** [comment]
It can be closed, I agree it's not very actionable for you. In fact I've just overruled this template in my app. However some points I made still stand. ;)

**Comment by tf** [comment]
Ok. Just let me know if there is anything I can be helpful with.
