### ISSUE TITLE
content_for :head in analytics caching issue

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#471]
I use `content_for :head` in the [analytics partial](https://github.com/scrollytelling/app/blob/a499c125eec7f0b6fd87a8b96f4b00653472c38c/app/views/pageflow/entries/_analytics.html.erb) but it keeps disappearing. I strongly suspect a caching issue.

I fully realise that my partial, linked above, is quite ugly. But I need different trackers for different accounts and sometimes different themes. That is not the point. I think [this line](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/pageflow/entries/show.html.erb#L34) should be placed outside the caching block regardless.

**Comment by tf** [comment]
Well, yes and no. Since the partial is cached, you cannot use `content_for :head` inside of it. Still, I believe the partial should be cached since rendering it can be expensive with multiple database queries.

For widget types there is [`render_head_fragment`](https://github.com/codevise/pageflow/blob/master/lib/pageflow/widget_type.rb#L35) which is [cached separately](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/pageflow/entries/show.html.erb#L10). So I'd argue that the analytics partial is simply not powerful enough to achieve what you are trying to do and advice you to use widget types. Otherwise their would need to be some sort of `analytics_head_fragment` partial, which I'd not be super-excited to add since the functionality is there on a a more general level via widget types and the analytics partial wasn't that great of an abstraction to begin with.

**Comment by tilsammans** [comment]
I see. I'll dive into widgets. Thanks!

**Comment by tilsammans** [comment]
@tf I am having a hard time getting my WidgetType to work. I am following the [readme](https://github.com/codevise/pageflow/blob/master/doc/creating_widget_types.md) but this line has me paused:

> At this point widgets of the new type can be associated with entries and will be rendered.

How exactly? I do see the widget as dropdown in the Account, but doesn't seem to have any effect. How can I associate a widget with an entry?

**Comment by tilsammans** [comment]
Never mind, the dropdown appeared in the story editor just now. Weird, wasn't there before.

**Comment by tf** [comment]
Choosing the widget on account level only makes it the default for new entries. Another option is to register the widget type as default in the initializer which enables the widget for all entries including existing ones. The drop down in the editor is only displayed if there is more than one widget type registered for a role. This is a workaround to prevent editors from being confused by too many drop downs with no real choices. The drop down is present in the DOM though and can be displayed via the dev tools. There should probably be better authorization integration, displaying only some drop downs to editors and all of them for admins or something.

**Comment by tilsammans** [comment]
My idea exactly. I will send you mail about it.
