### ISSUE TITLE
undefined method `authenticate_user!' for #<Admin::DashboardController:0x007fe157deaea0>

### ISSUE THREAD

**Issue by vetm73** [codevise/pageflow#495]
Hi,

I managed to install the application. When I go to http://127.0.0.1:3000/admin I get the error:

undefined method `authenticate_user!' for #<Admin::DashboardController:0x007fe157deaea0>

When I go to http://127.0.0.1:3000/admin/login I get:

No route matches [GET] "/admin/login"

Rails.root: /home/mike/pageflow/my_pageflow

Kind regards,

Mike

**Comment by tf** [comment]
Hi Mike,

did the `pageflow:install` generator run without errors? Could you paste your `Gemfile.lock` and your `config/routes.rb` into a gist and post a link here?

Cheers
Tim

**Comment by vetm73** [comment]
Hi Tim,

I had some trouble installing the right versions of Ruby and Rails but thereafter it completed without an error.

Here are my files:

https://gist.github.com/vetm73/62c2c978cb2ace62aa9e

Cheers,

Mike

**Comment by tf** [comment]
From what it looks like, the generator did not run successfully. There are several entries missing in the routes file. Please repeat the process and have another look whether there are error messages. If you are unsure, you can also copy the console output of running `rails generate pageflow:install` into the gist and let me have a look.

Please start with a newly generated Rails app again, since rerunning the generator in an app where it already ran and failed might lead to hard to track down follow up errors.

**Comment by vetm73** [comment]
Thanks, that did the trick!

**Comment by tf** [comment]
Happy to hear that! I'll close the issue now. Feel free to open a new one if other problems come up.
