### ISSUE TITLE
Thoughts on overriding translations

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#496]
I would like the ability to override certain `I18n` keys in my app, for instance `pageflow.editor.blank_entry.header` in [blank_entry.jst.ejs](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/assets/javascripts/pageflow/editor/templates/blank_entry.jst.ejs).

I could not find an easy way to go about this, because the order for `I18n.load_path` is set at initialisation time and changing it does not make a difference for keys that are looked up. I recall that you are currently working on the `I18n` or it has already been completed, I don't know.

Would you be open to moving the pageflow keys into a default, so that it becomes easier to set the `I18n` keys in the application itself?

```
<h2><%= I18n.t('editor.blank_entry.header', default: 'pageflow.editor.blank_entry.header') %></h2>
```

won't change a thing in terms of how Pageflow translates, but allows for much easier override in the main application.

**Comment by tf** [comment]
Work an I18n is done so far. Publicly visible translations live in the `pageflow-public-i18n` gem. All other admin/editor translations are supposed to stay inside their respective gems.

I'm a bit surprised overriding translations does not simply work. I just tried to put a yml file inside a Pageflow app defined a key and it got overridden. From looking at the `I18n.load_path`, it seems app locales come last.

More generally, I'm a bit worried since this effectively turns all translation keys into API surface. How would we handle UI changes? Would we have to keep a changelog of translation keys? 

Maybe we could add something more explicit, for certain keys which contain important marketing copy? I could see adding a new namespace `pageflow.backend` (or whatever editor and admin might be called together) of blessed keys that are promised to be kept around.

**Comment by tilsammans** [comment]
I'll retry to see if I can get it working, if you're saying (like I was thinking) it should work straight away.

**Comment by tilsammans** [comment]
@tf here is the issue, I've just push three translations to our Rails app. When I output the translated strings, I do see the `smoke_test` translation, but the others aren't picked up. So I still suspect an issue in the load order.

```
bin/rails runner 'puts I18n.t("pageflow.editor.blank_entry")'
{
  :create_chapter=>"Click <em>New chapter</em> to create your first chapter.",
  :create_page=>"Use the <em>New page</em> button within the chapter to add pages.",
  :edit_page=>"Click directly on a page to switch to the pages edit view.",
  :header=>"This is an empty Pageflow",
  :intro=>"Each Pageflow consist of chapters and pages. The editor panel to your right shows the outline of your story.",
  :outro=>"In this area, a live preview will be shown.",
  :smoke_test=>"Is this button on?"
}
```

**Comment by tf** [comment]
So what is the order in `I18n.load_path`?

Joost Baaij <notifications@github.com> schrieb am Di., 16. Feb. 2016, 09:01:

**Comment by tilsammans** [comment]
https://gist.github.com/tilsammans/d24925260642cd15c131

**Comment by tf** [comment]
Looks like your app's translations come up somewhere in the middle. I found that in applications which explicitly change the `I18n.load_path` in their `application.rb` app paths actually come last and thus can override translations:

```ruby
 config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.yml').to_s]
```

It remains to be checked whether this is also true in production. It would be really bad though if development and production env did no align here.

**Comment by tf** [comment]
I had to use this technique myself today. From that experience I can say that it works.

**Comment by tilsammans** [comment]
It works indeed! I needed to refresh the locale file and then clear the cache, and it worked.
