### ISSUE TITLE
Limit of 20 outputs per Zencoder job

### ISSUE THREAD

**Issue by wpd-tommi** [codevise/pageflow#536]
Hi, 
when I try to encode a video I'll get this error:

{"errors":["There is a limit of 20 outputs per job. If you need more outputs, contact us at help@zencoder.com.“]}

Is it possible to reduce or split the the outputs? The zencoder support says: "at this current time the outputs are hard capped at 20 for single jobs".
Thanks Tommi

**Comment by tf** [comment]
Hi Tommi,

that's strange. For us Pageflow only generates jobs with up to 11 outputs. Are you using SFTP outputs? We haven't used them ourselves in a long time. So maybe Zencoder policies changed since then. If you are only using S3 outputs, could you paste the JSON of one of your jobs from the Zencoder request builder into a gist and link it up here? 

Tim

**Comment by wpd-tommi** [comment]
[zencoder-error.txt](https://github.com/codevise/pageflow/files/314151/zencoder-error.txt)
Thanks Tim

**Comment by tf** [comment]
Ok, as I expected the SFTP outputs account for the additional items. When SFTP is configured, Pageflow  still makes Zencoder output files to S3 to allow switching between S3/SFTP setup at any point.

I see different options:
* We could look into adding a config option to disable S3 output. This is a larger endeavor, though, with some of the same challanges as #54.
* If I count correctly, your job definition contains 22 outputs. The generated SMIL files are mostly needed when using Akamai CDN. We could add an option to skip generation of SMIL files, thus leaving us with 20 jobs.
* As a last resort, we could split up encoding jobs. This would make the already involved encoding workflow a lot more complicated, though. 

Embarrassingly, the classes responsible for assembling Zencoder jobs ([[1]](https://github.com/codevise/pageflow/blob/master/lib/pageflow/zencoder_video_output_definition.rb), [[2]](https://github.com/codevise/pageflow/blob/master/lib/pageflow/zencoder_audio_output_definition.rb), [[3]](https://github.com/codevise/pageflow/blob/master/lib/pageflow/zencoder_output_definition.rb)) have no unit level test coverage at the moment. Historically, there was an integration test suite, which has not been ported to the gem since it was slow, hence was not run continuously, hence broke at some point.

So before we make any change in this area, we would have to look into getting some unit level test coverage. SFTP is not a priority for us at the moment. But if you would be interested in working on this issue, I'd be happy to provide pointers.

**Comment by wpd-tommi** [comment]
Hi Tim,
you are right with the SFTP outputs. We've disabled this and everything works fine. Many thanks for your help and solving this. Regards Tommi

**Comment by wpd-tommi** [comment]
Hi Tim,

we have solved this below, thanks again :-)

We have some problems to upgrade to the newest pageflow version. Is it
possible, that you help us directly on our server (Ubuntu 14.04 LTS) and
we pay you for that? Or is this kind of support not planed?

Thanks and Regards
Tommi

> Tim Fischbach <mailto:notifications@github.com>
> Dienstag, 14. Juni 2016 09:33
>
> Hi Tommi,
>
> that's strange. For us Pageflow only generates jobs with up to 11
> outputs. Are you using SFTP outputs? We haven't used them ourselves in
> a long time. So maybe Zencoder policies changed since then. If you are
> only using S3 outputs, could you paste the JSON of one of your jobs
> from the Zencoder request builder into a gist and link it up here?
>
> Tim
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codevise/pageflow/issues/536#issuecomment-225801909>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADoWurHw02IVOL_cCY5UY1w4OWSKmJewks5qLlkwgaJpZM4I1B7->.
>

-- 
wakeup page design
Tommi Nübling
Egonstr. 38
79106 Freiburg

0761 / 70 48 521
nuebling@wake.de
http://www.wake.de

**Comment by tf** [comment]
Hi Tommi,

while we would be open for such a cooperation in general, we do not have the resources at the moment. Things might be less busy mid September, but that might be too late for you.

Feel free to open issues for specific problems, though.  

Tim
