### ISSUE TITLE
Account delete should deal with entries

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#562]
When an account is deleted, something has to be done with its [entries](https://github.com/codevise/pageflow/blob/master/app/models/pageflow/account.rb#L6).

Either `nillify` or destroy, or the account destroy should be halted. Otherwise the admin pages can't deal with the missing account for the existing entry.

**Comment by tf** [comment]
Doesn't [this line](https://github.com/codevise/pageflow/blob/master/lib/pageflow/ability_mixin.rb#L45) prevent non empty accounts from being deleted?

**Comment by tilsammans** [comment]
It sure does. However I had a demo account deletion in a cronjob, which does not look at CanCan.

**Comment by tf** [comment]
I see. Maybe we could add a `before_destroy` callback as a second layer of security? The ability level check would still be needed to make active admin disable buttons correctly.

**Comment by tilsammans** [comment]
I've given this a lot of thought and very hesitant to add a `before_destroy` callback. In my experience they are nothing but pain. Suddenly a record won't be destroyed and there won't be any sort of error message to work with.

Maybe we should let this one go...

**Comment by tf** [comment]
Looking at the [docs of `has_many`](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many), there appears to be `dependent: :restrict_with_exception` option, that I did not know about before. It causes an exception to be raised when trying to destroy a record that is still referenced via the association. Given that prematurely deleting an account leaves our database in an inconsistent state, this might be an option. This appears to available since Rails 4.0.

**Comment by tilsammans** [comment]
That's a good find. I did not know about this before either.

It looks like this will fit the bill better. I will raise `ActiveRecord::DeleteRestrictionError`.

I'll work on a patch.
