### ISSUE TITLE
Mute video on iOS 10+

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#583]
iOS 10 will allow [video to autoplay when it's muted](https://webkit.org/blog/6784/new-video-policies-for-ios/). It will be great for Pageflow stories. Could we prepare for this change by muting video on that platform?

**Comment by tf** [comment]
Yes! This has been great news this week. We are currently starting to rework the video stack to leverage adaptive streaming on more platforms. At the same time we are planning to rewrite the video pages anyway based on the new React stack. This gives us a good opportunity to change the background video page type to make use of the new possibilities.

**Comment by tilsammans** [comment]
Any word on the progress of this issue? iOS 10 is out and adoption is very good. Close to half of all devices have it, so we think it's very worthwhile to offer it.

**Comment by tf** [comment]
We are currently working on a major overhaul of the complete video stack including background video support for most of the existing page types where so far only background images could be used. Our plan is to use muted videos in these scenarios by default. The normal video page type will still use the OS player since autoplaying a muted video does not make a lot of sense in this case if it means you miss the beginning of an interview etc.

In the light of the current work, it does not make sense for us to apply changes in this direction to the current code base. While I cannot give an exact timeline, I can say that these changes are high priority for us and are actively being worked on. We'll also try to partition the changes in a way that allows bringing intermediate steps to master as soon as possible.

**Comment by tilsammans** [comment]
Cool!

Universal background video is going to be awesome. Can't wait. Muting by default makes total sense.

**Comment by DaKaZ** [comment]
Any progress here?  We just implemented our first page flow and then realized mobile devices did not support the background video... I was going to start working on adding that support but if it is underway I don't want to duplicate efforts.  I am happy to help, just let me know how I can.

Thanks

**Comment by tf** [comment]
Hi,

this is what I'm currently finishing up. Much of the front end code has been rewritten in React/Redux (see [wip branch](https://github.com/tf/pageflow-react/tree/redux)) to support DASH and subtitles. We are doing a lot of testing and bug fixing at the moment. But I expect the release to happen this month.

**Comment by DaKaZ** [comment]
Ohhh, that is really exciting!  Did you use React on Rails for the rails side?  Nice work, I'll keep tabs on the new repo...

**Comment by tf** [comment]
This has now been released as part of Pageflow 12.
