### ISSUE TITLE
Adding text fade animations

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#669]
We'd like to add three text fade animations (specifically, fade-in-out) to the list of currently available animations (all fade in with various timings).

Is there a documented way to add these?

Additionally, I'd like to propose renaming this feature. The name is currently "fade in text after delay". This could become "text effect" (like transition effect) and the effects currently present could be named "fade in - short delay" etc.

Is this doable?

**Comment by tf** [comment]
The feature is not documented anywhere since it is a bit spread out among different places in the code base. Still, I'd expect the proposed change to be rather straight forward.

Just to understand this better: What does fade-in-out mean?

The relevant places in the code base are:

- The list of available effects [lives inside the editor `Page` model](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/editor/models/page.js#L86). You would have to add items here.
- There's a [shared group of input fields](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/editor/views/configuration_editors/groups/options.js#L11) which makes the setting available for all page types. No change should be needed here.
- For published entries a corresponding css class [is applied to the page element](https://github.com/codevise/pageflow/blob/master/app/helpers/pageflow/pages_helper.rb#L18). This should also just work for new options.
- Inside the editor this class [is kept in sync](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/page_types/mixins/common_page_css_classes.js#L7) with the current value of the setting. Again, no change needed, I think.
- Finally, there are [styles to define what the concrete animations look like](https://github.com/codevise/pageflow/blob/master/app/assets/stylesheets/pageflow/delayed_text_fade_in.scss). This part especially is a bit awkward since it introduces coupling to concrete CSS class names of different page components and introduces the risk of collisions should there ever be a different reason to apply an `animation` to one of the elements.   

The proposed naming change sounds fine. Search for `delayed` in `config/locales/{en,de}.yml` to see the relevant translations and places to add translations for new options. To stay backwards compatible, I'd suggest just changing the translations not the possible values itself (which are also just called `short`, not `fade_in_short` at the moment).

**Comment by tilsammans** [comment]
We'd like the option to fade in text, and fade it out again. We're using this in [our fork of the linkmap page type](https://github.com/scrollytelling/pageflow-linkmap-page/blob/f6c65946ffec0763960d01d65c5971dd478f9911/app/assets/stylesheets/pageflow/linkmap_page.css.scss#L19). It's a few lines of CSS.

If you don't mind pulling these animations into Pageflow proper, I can do that do. Otherwise I'd have to think about a way to pull this out, so it can be extended. What do you think?

**Comment by tf** [comment]
Given the mentioned coupling to CSS internals, I don't see any good way to make this extensible. So I'd be open to including it in core. If edge cases should come up, we can still put the new text effects behind a feature flag.

**Comment by tf** [comment]
Given the mentioned coupling to CSS internals, I don't see any good way to make this extensible. So I'd be open to including it in core. If edge cases should come up, we can still put the new text effects behind a feature flag.

**Comment by tilsammans** [comment]
I'll draw up a pull request in the coming weeks.

One thing I noticed is that the gradient animation is not coupled with these text delays. This means that the gradient appears (via separate timings) but it never goes away. The effect is not great when the text itself _does_ go away. Not sure how to solve this yet, although my gut feeling is that appearance of the gradient should be coupled with all text effects.
