### ISSUE TITLE
Cannot send invitations to new users

### ISSUE THREAD

**Issue by jtebbenGS** [codevise/pageflow#731]
There is a strange error in the user administration that our environment is experiencing. We can create a new user request, however no email is sent or re-sent (via profile page) to allow that user to come and complete their registration. I initially thought this was because mail wasn't configured, however the logs point to a potential activeadmin issue:

 `E, [2017-03-09T10:53:52.080366 #21932] ERROR -- : Unable to deliver email [invitation]: Couldn't find User with 'id'=
E, [2017-03-09T10:53:52.080638 #21932] ERROR -- : /var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:155:in `find'
	/var/lib/gems/2.1.0/gems/pageflow-0.11.3/app/mailers/pageflow/user_mailer.rb:7:in `invitation'`

In lieu of getting the admin pages resolved, is there an alternate way to create users and get them registered safely?

Attached is the GemFile if that's of any help (ignore the mess....)
[Gemfile.txt](https://github.com/codevise/pageflow/files/831733/Gemfile.txt)

**Comment by tf** [comment]
There was an [unintended breaking change](https://github.com/zapnap/resque_mailer/issues/100) in `resque-mailer` 2.4.1, which has since been fixed in version 2.4.2, that can cause an exception like that. Can you check if you happen to use the affected version of that gem?

There is no other user sign up path in Pageflow. Since Pageflow uses Devise, you are always free to add some sort of self sign up by yourself, though, for example.
