### ISSUE TITLE
entry and account broken on Membership

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#772]
On my machine, these two relationships on `Pageflow::Membership` fail:

```
m = Pageflow::Membership.last
m.entry # => ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'pageflow_memberships.entity_type' in 'where clause': SELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`id` = 6 AND `pageflow_memberships`.`entity_type` = 'Pageflow::Entry' LIMIT 1
m.account # => Mysql2::Error: Unknown column 'pageflow_memberships.entity_type' in 'where clause': SELECT  `pageflow_accounts`.* FROM `pageflow_accounts` WHERE `pageflow_accounts`.`id` = 6 AND `pageflow_memberships`.`entity_type` = 'Pageflow::Account' LIMIT 1
```

The reason is that `pageflow_memberships` isn't included in the query.

**Comment by tf** [comment]
These two associations are more a less a hack to circumvent Rails' restrictions around eager loading polymorphic associations. The "real" association is `Membership#entity`. But, for example, in the [`UserAccountsTab`](https://github.com/codevise/pageflow/blob/master/app/views/components/pageflow/admin/user_accounts_tab.rb#L6) we want to list all accounts a user is member of and need a way to eager load the accounts to display their names without doing N+1 queries.

We cannot do `user.memberships.on_accounts.includes(:entity)` since Active Record does not support eager loading polymorphic associations. So instead we do `user.memberships.on_accounts.includes(:accounts).references(:pageflow_accounts)` to ensure the `pageflow_accounts` table is joined. In this specific scenario the condition in `Membership#account` can actually reference `pageflow_memberships`.

If the condition wasn't there, we would possibly eager load both associations with a model matching the `entity_id` disregarding `entity_type`:

```
   user.memberships.first.entity # => #<Pageflow::Account id: 1>
   m = user.memberships.includes(:account, :entry).first
   m.first.entry # => #<Pageflow::Entry id: 1>
```
With the condition in place, `m.first.entry` is nil.

I'd love to know a better way to handle such situations, but I currently don't.

**Comment by tilsammans** [comment]
I see!

I guess I can think of alternative schemas where this particular problem doesn't appear, but other problems definitely would. So it's fine, I'll use `:references` when I want to get at these relations.
