### ISSUE TITLE
Allow page modifications via JavaScript

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#855]
in [pageflow-oembed](https://github.com/scrollytelling/pageflow-oembed) we've added DOM manipulations to create embedded content on the fly.

In Pageflow 12, based on React, this will no longer work.

We probably need an official React API for us to hook into, so that we can modify page props. There are good npm for embedding content available.

**Comment by tf** [comment]
I basically see two routes with different trade-offs:

#### Adding an API to insert React components into pages.

This would probably be the quickest way to re-enable the `pageflow-oembed` functionality. If we made this part of one of the generic page components (e.g. the `PageText` component), it would be available for all React-based page types without further changes.

Still, my gut tells me that "hey, insert anything here" might be a too generic abstraction :wink:. Especially when I think about advanced page layout and text positioning features that we might want to incorporate somewhere down the line, having to deal with arbitrary components that live on the same level of the DOM hierarchy might be a source of extra complexity.

#### Adding an API to enhance the page HTML with embeds

Maybe there is some angle that I am missing, but rendering the embed all the way below the last paragraph always looked like a compromise to me. If I mention a twitter URL in the first paragraph, I would like the embed to show up somehow near that position in the text.

Given that in the future there might be additional HTML artifacts living inside of our page text anyway (like block quotes or lists), we could consider adding a way to post-process the page HTML right before displaying it in order to dynamically insert additional such artifacts (i.e. embeds).

The rich text editor could be extended to include additional buttons, to allow plugins to define placeholders that can be inserted in the stored HTML. In server side rendering these could just be stripped out. But in the browser, once the HTML has been rendered to the DOM (which happens using [dangerouslySetInnerHTML](https://github.com/codevise/pageflow/blob/master/node_package/src/components/PageText.jsx#L19) anyway) the placeholder elements could be passed to corresponding processors which turn them into something else. 

We would need to handle the React life cycle of the `PageText` component with some care to make sure processing reoccurs once the contents is re-rendered, but that way we might even end up with a React-agnostic API, which one might see as a pro or a con but would match the way page type and widget type APIs work at the moment. The DOM inserted for the placeholder might still be rendered with React, but that would the implementer's choice .

**Comment by tilsammans** [comment]
> Maybe there is some angle that I am missing, but rendering the embed all the way below the last paragraph always looked like a compromise to me.

This is not what we were doing though.

> If I mention a twitter URL in the first paragraph, I would like the embed to show up somehow near that position in the text.

This is what we were doing. 😄 

The oEmbed plugin actually would like to plug into the server-side rendering as well. All providers except Twitter have regular HTML snippets that we fetch and store locally. It would be great if there were a documented way to add a filter to page content, so that we can replace on the fly.

A simultaneous step would be to allow some kind of client-side rendering.

I wouldn't mind the first approach, actually subclassing the 'official' component seems pretty intuitive to me.

**Comment by tf** [comment]
> This is what we were doing. :smile:

Turns out I don't know `pageflow-oembed` too well. :wink: 

But that basically rules out my option 1 (single insert point for new components below `PageText`).

> The oEmbed plugin actually would like to plug into the server-side rendering as well. 

Agreed. This rules out my option 2 since the described API would be pretty DOM-centric. 

Our "store HTML in the database" approach does not make filtering that easy. The only thing that comes to mind at the moment would be to actually do text replacement on the stored HTML to turn placeholders into custom rendered HTML. If we used React to render the custom HTML, the functionality could be server and client side compatible.

Overriding and replacing official components looks like the worst of all worlds to me. From my experience, sub classing is mostly an antipattern in React. It breaks encapsulation of official components in a complicated way and will be hard to stay compatible when components evolve. Given that there would need to be an API to allow swapping in the subclassed components, I'd feel like encouraging the wrong kind of extensions.

**Comment by tilsammans** [comment]
Is unmounting React an option? At least for the short term?

Or—just freewheeling here—cloning the DOM, hiding the React output allowing simple DOM manipulations to occur on the clone?

**Comment by tf** [comment]
Sorry for not getting back earlier. Maybe returning `false` from `PageContent#shouldComponentUpdate` when not inside the editor, could be a temporary solution? That could at least make it work in published entries. `pageflow-oembed` would still somehow need to make sure not to make changes to the server side rendered DOM, but wait until the page is rehydrated. But with that change, it could be sure, DOM inside `PageContent` does not change anymore after that. There is a boolean `PAGEFLOW_EDITOR` global, which could be used for this detection.

To make it work inside the editor and as a longer term solution, I still think the page content filtering API is worth pursuing.

**Comment by tf** [comment]
see #914 for a rough first stab at how page text embeds might work.
