### ISSUE TITLE
'undefined' videos

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#869]
After upgrading to Pageflow 12, I am seeing 'undefined' in the console. For example this URL: https://achtergrond.omroepbrabant.nl/tijn-een-eeuwig-mooi-verhaal#8987

What could be the cause of this? Do I need to re-encode these videos at Zencoder? Will that be required for all previously published videos?

**Comment by tf** [comment]
This will be #867. It does not happen for newly encoded files, rigtht? I'm just realizing now that I'll have to release 12.0.2 to fix that.

We are storing in the DB which video variants have been generated by Zencoder. For legacy files, the migration fills that info in with defaults. The list was missing HLS. This had not come up earlier since all other systems we updated used Akamai generated HLS files.

As a hotfix you can update your `pageflow_video_files` table and set `output_presences` to 

    {"high":true,"medium":true,"low":true,"hls-playlist":true}

for files that have the former default value

    {"high":true,"medium":true,"low":true}

set.

**Comment by tf** [comment]
I'll start working a migration to release as 12.0.2 right now. Maybe you can then already use that to apply the fix.

**Comment by tf** [comment]
Travis is failing due to some issue with `capybara-webkit` (which we still use on `12-0-stable`). I'll try to solve it now, but you can already take a look at the migration if you want.

**Comment by tf** [comment]
12.0.2 has been released including [some more bug fix backports](https://github.com/codevise/pageflow/blob/12-0-stable/CHANGELOG.md#version-1202). I should probably  also include the migration in 12.1 instead of just fixing the old one, otherwise people going straight from 12.0.1 to 12.1 will miss it, right?

**Comment by tilsammans** [comment]
> I should probably also include the migration in 12.1 instead of just fixing the old one, otherwise people going straight from 12.0.1 to 12.1 will miss it, right?

Yep.

Which is fine, because I think the migration is non-idempotent anyway.

**Comment by tf** [comment]
see #872

**Comment by tilsammans** [comment]
Pageflow 12.0.2 fixed the issue. [commit](https://github.com/scrollytelling/app/commit/9540dd599f37c4f49e133455ae846891ab4ac650) 🙌
