### ISSUE TITLE
Error in Aws host and alias

### ISSUE THREAD

**Issue by tssh-dev** [codevise/pageflow#896]
My bucket name is demobucket. AWS bucket region is "eu-east-2" and ec2 instance url is "ec2-xx-xxx-xx-xx.us-east-2.compute.amazonaws.com" like this can anyone tell me what are the values for 

s3_host_name
s3_host_alias

I am stuck at this point image is not uploading to s3 and one more thing for image uploading is Zencoder is necessary?  

I get this error

```
[AWS S3 200 309.424513 10 retries] put_object(:acl=>:public_read,:bucket_name=>"mypageflow",:cache_control=>"public, max-age=31536000",:content_length=>6053,:content_type=>"image/jpeg",:data=>Paperclip::UploadedFileAdapter: job_post.jpeg,:key=>"/image_files/unprocessed_attachments/000/000/005/original/job_post.jpeg") SocketError getaddrinfo: Name or service not known

   (54.7ms)  ROLLBACK
Completed 500 Internal Server Error in 310366ms (ActiveRecord: 751.1ms)
```

SocketError (getaddrinfo: Name or service not known):

**Comment by aviav** [comment]
Did you already try to follow the docs at [1]? In principle, you can try to clone `pageflow` ([2]) and do `git grep s3_host_name` in future cases that are similar to this one. 

In case you already follow the docs, please comment again. Otherwise, you can close this issue.

[1] https://github.com/codevise/pageflow/blob/master/doc/setting_up_external_services.md
[2] https://github.com/codevise/pageflow.git

**Comment by tssh-dev** [comment]
Yes I created two different buckets 1. demobucket 2. demobucket-out and followed doc [1]
I just want to know 
```
s3_host_name: "s3-eu-east-2.amazonaws.com"
s3_host_alias: "demobucket-out.ec2-18-220-16-46.us-east-2.compute.amazonaws.com
s3_host_alias: "demobucket.ec2-18-220-16-46.us-east-2.compute.amazonaws.com
```

is that right for both buckets as I am getting error

```
SocketError getaddrinfo: Name or service not known

   (69.4ms)  ROLLBACK
Completed 500 Internal Server Error in 317765ms (ActiveRecord: 225.9ms)
```

**Comment by tssh-dev** [comment]
Steps did for bucket configuration
1. Configure static website hosting for each bucket.
2. Grant access to the buckets by adding bucket policies.
3. Enable Cross-Origin Resource Sharing (CORS).

Zencoder Also enabled
the only thing in which  I am not sure is s3_host_alias is that right or not.
Redis is running in the background.

**Comment by aviav** [comment]
Bucket configuration sounds fine then.

To be more direct, I assume you might not have followed advice to see the list of S3 AWS endpoints for more information. If you do that, you might conclude that your aliases do not have the form of an S3 Website endpoint.

I can see how my two previous comments on this issue might come across as unhelpful. Things you could do to get ahead more quickly in the future and at the same time express some gratitude and empathy:

1) Include relevant info like 'I followed these docs by ..., including setting up the bucket config' from the start. I acknowledge that it can be challenging to identify what is relevant info in any given case, but the alternative is that I have to pull that info from you by first finding out myself what you probably have done and have not done.
2) Even better, read the relevant docs entirely, and try to become aware of terms that are unclear to you. In this case, 'S3 Website endpoint' is a term that is out of scope for Pageflow docs, because Amazon invests a lot into their own docs already, which we even link to in the docs that you follow.
3) Best, in addition to 2), become aware of something about Pageflow's docs that made you miss the relevant info, and try to come up with a PR for the docs, which I'll gladly review, and in case we agree that they improve matters, merge.

I hope you can see that I endeavored to resolve this issue with kind and compassionate intent, even though we needed some conversation here :-)

If I assume correctly that this comment of mine resolves this specific issue for you, you can close. Otherwise, please comment again

**Comment by tssh-dev** [comment]
Hi @aviav, Thanks for your such fast and clear response to my unclear response.

I go through AWS S3 endpoints in  and in above link that you mentioned doc[1].

`s3_host_alias: 'com-example-pageflow.s3-website-eu-west-1.amazonaws.com' -> example`

as my site url is -> `ec2-18-220-16-46.us-east-2.compute.amazonaws.com`
and bucket region is -> `US East (ohio)`
for that region end point is -> `s3.us-east-2.amazonaws.com`

so by that, I made host_alias like this 
`s3_host_alias: "demobucket.ec2-18-220-16-46.us-east-2.compute.amazonaws.com`

and in my bucket it show endpoint is 

`"http://mypageflow.s3-website.us-east-2.amazonaws.com"`

so which one is right or should I have to modify?

**Comment by aviav** [comment]
To quote the documentation,

* `s3_host_alias`: [...] Even though use
  of a CDN is strongly recommended, you can also use an S3 Website
  endpoint here, as in the example above.

This part of the documentation is likely relevant for you. You already know what an S3 Website endpoint is, so you can probably use this part of the docs by now.

Your question was reasonably clear, and I on my part thank you for your readiness to elaborate further and to do research using available documentation. I just wanted to point out to you how you can use available resources more efficiently in the future.

In case you can find the answer now, please close this issue. Otherwise, you are welcome to comment.

**Comment by tssh-dev** [comment]
Hi @aviav I am using `http://demobucket.s3-website.us-east-2.amazonaws.com` this as host_alias and getting this as log and after waitng for 3-4 minutes the messages comes `Uploading failed` in Pageflow editor

```
Processing by Pageflow::Editor::FilesController#create as JSON
  Parameters: {"authenticity_token"=>"9dGenbiwucf9hPerCeMjyYsxKco02b2pTLdJ8Ev533JsIQfPUQLvKvBwgT5oWlhNUikgm3DTcFBwwohu2ekUeQ==", "image_file"=>{"rights"=>"", "configuration"=>{"alt"=>""}, "attachment"=>#<ActionDispatch::Http::UploadedFile:0x007fed871fb978 @tempfile=#<Tempfile:/tmp/RackMultipart20171108-3875-r7zapi.jpeg>, @original_filename="query.jpeg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"image_file[attachment]\"; filename=\"query.jpeg\"\r\nContent-Type: image/jpeg\r\n">}, "entry_id"=>"5", "collection_name"=>"image_files"}
  [1m[36mUser Load (0.2ms)[0m  [1mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1[0m
  [1m[35mPageflow::Entry Load (0.2ms)[0m  SELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`slug` = '5' LIMIT 1
  [1m[36mPageflow::Entry Load (0.2ms)[0m  [1mSELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`id` = 5 LIMIT 1[0m
  [1m[35mPageflow::Revision Load (0.2ms)[0m  SELECT  `pageflow_revisions`.* FROM `pageflow_revisions` WHERE `pageflow_revisions`.`entry_id` = 5 AND (frozen_at IS NULL) LIMIT 1
  [1m[36mPageflow::EditLock Load (0.1ms)[0m  [1mSELECT  `pageflow_edit_locks`.* FROM `pageflow_edit_locks` WHERE `pageflow_edit_locks`.`entry_id` = 5 LIMIT 1[0m
  [1m[35mUser Load (0.1ms)[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  [1m[36m (0.1ms)[0m  [1mBEGIN[0m
  [1m[35mSQL (0.1ms)[0m  UPDATE `pageflow_edit_locks` SET `pageflow_edit_locks`.`updated_at` = '2017-11-08 06:12:27' WHERE `pageflow_edit_locks`.`id` = 12
  [1m[36m (2.0ms)[0m  [1mCOMMIT[0m
Unpermitted parameters: rights, configuration
Unpermitted parameters: rights, configuration
Unpermitted parameters: configuration, attachment
Unpermitted parameters: rights, configuration, attachment
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/1b1cc7f086b3f074da452bc3129981eb20171108-3875-11urud3.jpeg[0]' 2>/dev/null
  [1m[35m (0.1ms)[0m  BEGIN
  [1m[36mSQL (0.2ms)[0m  [1mINSERT INTO `pageflow_image_files` (`unprocessed_attachment_file_name`, `unprocessed_attachment_content_type`, `unprocessed_attachment_file_size`, `unprocessed_attachment_updated_at`, `width`, `height`, `state`, `entry_id`, `created_at`, `updated_at`) VALUES ('query.jpeg', 'image/jpeg', 6926, '2017-11-08 06:12:27', 228, 221, 'not_processed', 5, '2017-11-08 06:12:27', '2017-11-08 06:12:27')[0m
[paperclip] saving ip-172-31-29-56/image_files/unprocessed_attachments/000/000/008/original/query.jpeg


Started GET "/entries/5" for 117.247.227.115 at 2017-11-08 06:12:27 +0000
Cannot render console from 117.247.227.115! Allowed networks: 103.219.213.145, 127.0.0.0/127.255.255.255, ::1
Processing by Pageflow::EntriesController#show as JSON
  Parameters: {"id"=>"5"}
  [1m[35mUser Load (0.3ms)[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  [1m[36mPageflow::Entry Load (0.2ms)[0m  [1mSELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`slug` = '5' LIMIT 1[0m
  [1m[35mPageflow::Entry Load (0.1ms)[0m  SELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`id` = 5 LIMIT 1
  [1m[36mPageflow::Revision Load (0.2ms)[0m  [1mSELECT  `pageflow_revisions`.* FROM `pageflow_revisions` WHERE `pageflow_revisions`.`entry_id` = 5 AND (frozen_at IS NULL) LIMIT 1[0m
  [1m[35mSQL (0.3ms)[0m  SELECT `pageflow_image_files`.`id` AS t0_r0, `pageflow_image_files`.`entry_id` AS t0_r1, `pageflow_image_files`.`uploader_id` AS t0_r2, `pageflow_image_files`.`unprocessed_attachment_file_name` AS t0_r3, `pageflow_image_files`.`unprocessed_attachment_content_type` AS t0_r4, `pageflow_image_files`.`unprocessed_attachment_file_size` AS t0_r5, `pageflow_image_files`.`unprocessed_attachment_updated_at` AS t0_r6, `pageflow_image_files`.`processed_attachment_file_name` AS t0_r7, `pageflow_image_files`.`processed_attachment_content_type` AS t0_r8, `pageflow_image_files`.`processed_attachment_file_size` AS t0_r9, `pageflow_image_files`.`processed_attachment_updated_at` AS t0_r10, `pageflow_image_files`.`state` AS t0_r11, `pageflow_image_files`.`created_at` AS t0_r12, `pageflow_image_files`.`updated_at` AS t0_r13, `pageflow_image_files`.`width` AS t0_r14, `pageflow_image_files`.`height` AS t0_r15, `pageflow_image_files`.`rights` AS t0_r16, `pageflow_image_files`.`parent_file_id` AS t0_r17, `pageflow_image_files`.`parent_file_model_type` AS t0_r18, `pageflow_file_usages`.`id` AS t1_r0, `pageflow_file_usages`.`revision_id` AS t1_r1, `pageflow_file_usages`.`file_id` AS t1_r2, `pageflow_file_usages`.`file_type` AS t1_r3, `pageflow_file_usages`.`created_at` AS t1_r4, `pageflow_file_usages`.`updated_at` AS t1_r5, `pageflow_file_usages`.`configuration` AS t1_r6 FROM `pageflow_image_files` LEFT OUTER JOIN `pageflow_file_usages` ON `pageflow_file_usages`.`file_id` = `pageflow_image_files`.`id` AND `pageflow_file_usages`.`file_type` = 'Pageflow::ImageFile' WHERE `pageflow_file_usages`.`revision_id` = 5
```

**Comment by tssh-dev** [comment]
Hi I got this error

aws_host_alias is -> http://mybucket.s3-website.us-east-2.amazonaws.com

```
(52.5ms) COMMIT
Unpermitted parameters: rights, configuration
Unpermitted parameters: rights, configuration
Unpermitted parameters: configuration, attachment
Unpermitted parameters: rights, configuration, attachment
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/d5f016b090a4e2b6828cc44d0b46a91320171109-8095-1khn4d4.jpeg[0]' 2>/dev/null
(0.1ms) BEGIN
SQL (0.3ms) INSERT INTO pageflow_image_files (unprocessed_attachment_file_name, unprocessed_attachment_content_type, unprocessed_attachment_file_size, unprocessed_attachment_updated_at, width, height, state, entry_id, created_at, updated_at) VALUES ('job_post.jpeg', 'image/jpeg', 6053, '2017-11-09 06:46:19', 300, 168, 'not_processed', 3, '2017-11-09 06:46:20', '2017-11-09 06:46:20')
[paperclip] saving user063/image_files/unprocessed_attachments/000/000/004/original/job_post.jpeg

[AWS S3 200 320.419777 10 retries] put_object(:acl=>:public_read,:bucket_name=>"mypageflow",:cache_control=>"public, max-age=31536000",:content_length=>6053,:content_type=>"image/jpeg",:data=>Paperclip::UploadedFileAdapter: job_post.jpeg,:key=>"ptiweb063/image_files/unprocessed_attachments/000/000/004/original/job_post.jpeg") SocketError getaddrinfo: Name or service not known

(57.9ms) ROLLBACK
Completed 500 Internal Server Error in 322045ms (ActiveRecord: 113.2ms)

SocketError (getaddrinfo: Name or service not known):
```

**Comment by tssh-dev** [comment]
Hi @aviav 

I did some editing and image is uploading now but after that in processing 

this is the error 

`No Such Key - cannot copy ip-xxx-xx-xx-xx/image_files/unprocessed_attachments/000/000/012/original/sports.jpg to local file /tmp/088495f30901580ddd5171531cd2664920171109-21734-1phhvln.jpg`

Can you please tell me about that ? and I am using Zencoder test accout (free)

**Comment by aviav** [comment]
No Such Key is an error that Paperclip gets from S3.

One common reason for this to happen is that Resque workers need to be restarted after changing configuration.

In case you are sure you did that, maybe there is really some S3 key missing for some reason.

**Comment by tssh-dev** [comment]
Actually I know the problem, I removed `s3_host_alias` and `s3_host_name` from `config.paperclip_s3_default_options.merge` . After removing them image uploading is working.

I don't get the right value for these two

these are the values that I am using, don't know what is wrong with them.

`s3_host_name: "s3-eu-east-2.amazonaws.com`
`s3_host_alias: "demobucket.ec2-xx-xx-xx-xx.us-east-2.compute.amazonaws.com`

**Comment by aviav** [comment]
The s3-website one is correct in principle. Maybe try dropping `http://`. Also, I am using the `-` convention here, but that should not make a difference according to Amazon's docs.

Depending on your setup, after you change these variables, you might have to restart Resque workers by hand, because they might cache old values. Also depending on your setup, Spring might need to be stopped (`bin/spring stop`)

**Comment by tssh-dev** [comment]
Hi, @aviav Thanks a lot for your help. Now Image and audio files are uploading successfully.

But there is one thing I started resque workers by these commands and they are working good but after some time they'll get stopped and image uploading has also been stopped when I restart these workers then It will start working again.
```
rake resque:scheduler
QUEUE=* bundle exec rake resque:work
```

**Comment by aviav** [comment]
For automatic stability, you could look into setting up Monit [1], for example. What you choose to do specifically also has to depend on your deployment choices

[1] https://mmonit.com/monit/

**Comment by tf** [comment]
I'll close this issue now since I believe the original problem has been resolved. Feel free to open a new issue or post a reply here if the problem still persists.
