### ISSUE TITLE
Fix bourbon deprecations

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#933]
WARNING: box-shadow is deprecated and will be removed in the next major version release
WARNING: background-size is deprecated and will be removed in the next major version release

DEPRECATION WARNING: Passing 100%, a non-string value, to unquote()
will be an error in future versions of Sass.

**Comment by DanielKuhn** [comment]
`DEPRECATION WARNING: Passing 100%, a non-string value, to unquote()
will be an error in future versions of Sass.` refers to an implementation within the bourbon gem itself (`bourbon-3.1.8/app/assets/stylesheets/helpers/_deprecated-webkit-gradient.scss:27`), so that warning would disappear when upgrading the bourbon gem.

`background-size: cover` (used in `pageflow/app/assets/stylesheets/pageflow/page_types/background-image.scss`) should be safe to use by now, at least for newer browsers (https://caniuse.com/#feat=background-img-opts)

`box-shadow` (used in `pageflow-outline-navigation-bar/app/assets/stylesheets/pageflow/outline_navigation_bar/themes/default/parent_page_button.scss:43`,  `pageflow/app/assets/stylesheets/pageflow/themes/default/background_media_unmute_button.scss:41` and `pageflow/app/assets/stylesheets/pageflow/navigation_mobile.scss:135`) can safely be converted to the plain CSS attribute instead of the mixin

**Comment by DanielKuhn** [comment]
`box-shadow` warnings removed in https://github.com/codevise/pageflow-outline-navigation-bar/pull/7 and https://github.com/codevise/pageflow/pull/1070 (in accordance with https://github.com/thoughtbot/bourbon/issues/156)

`background-size` warning removed in https://github.com/codevise/pageflow/pull/1070

The `unquote`-warning is a little trickier to remove: It's caused by the `linear-gradient`-mixin in `pageflow/app/assets/stylesheets/pageflow/mixins/buttons.scss:59` which is deprecated in newer versions of bourbon. We need to replace that mixin when upgrading bourbon

**Comment by tf** [comment]
With our focus shifting to Pageflow Next, we have no plans to apply fixes like this to Pageflow Paged.
